### ISSUE TITLE
Cant fetch forklift

### ISSUE THREAD

**Issue by KindCoder-no** [DonHulieo/don-forklift#10]
I can't fetch a forklift from the "garage" NPC. Have tried both with and without qb-target enabled.

I can take an order and the pallet shows up. The truck on the outside also appears. But when I go to the forklift NPC, I cant take out a forklift.

Working:
![image](https://github.com/DonHulieo/don-forklift/assets/40148297/c61e6fef-f6d0-46ea-9f5a-42be8a9f3b09)
![image](https://github.com/DonHulieo/don-forklift/assets/40148297/05007a5c-357b-4ebd-b3f5-0946eeaaee76)
![image](https://github.com/DonHulieo/don-forklift/assets/40148297/9833d08f-c1cc-44a9-acf6-5ef3b77f51b7)

Not working:
![image](https://github.com/DonHulieo/don-forklift/assets/40148297/e872fc01-7a69-4c8c-ba76-b910c3a2950a)

**Comment by DonHulieo** [comment]
Hi mate, so a few things; 
- Is there any errors on the client or server console (as they'd help immensely with narrowing down the issue).
- Have you set ` Config.FuelSystem` correctly as an error there _may_ prevent the forklift from spawning.
- Is the forklift name or hash correctly declared in `Config.Locations[index]['Garage'].model`?

**Comment by KindCoder-no** [comment]
Hi.
- No errors in console
- Correct Fuelsystem
- The forklift model is the default model from config here on github

**Comment by KindCoder-no** [comment]
See attached image of logs in client, and server
![image](https://github.com/DonHulieo/don-forklift/assets/40148297/b71d277f-9ee4-40b9-8048-558401f4c26b)
![image](https://github.com/DonHulieo/don-forklift/assets/40148297/e99e9545-226a-4851-9ca6-03ac71f73008)

**Comment by George-Adam** [comment]
Commenting out lines 15, 28 and 41 in server/main.lua worked out for me (quick workaround, not really tested or recommended)

**Comment by Brave-developments** [comment]
same issue

**Comment by DonHulieo** [comment]
Latest updates should rectify vehicle retrieval issues.
