### ISSUE TITLE
Typo !

### ISSUE THREAD

**Issue by Krizmatic** [DonHulieo/don-forklift#2]
![image](https://user-images.githubusercontent.com/58721529/145785320-882f5650-0348-4319-becf-62682fa1d27d.png)

**Comment by DonHulieo** [comment]
Thank you, working on fixing this atm

**Comment by DonHulieo** [comment]
Should be good now boss

**Comment by Krizmatic** [comment]
![image](https://user-images.githubusercontent.com/58721529/145845122-ad454371-73c3-4e02-a6c8-cb3484f456fd.png)

**Comment by Krizmatic** [comment]
Again this one
