### ISSUE TITLE
[Enhancement] Update to new styles

### ISSUE THREAD

**Issue by nzkfc** [DonHulieo/don-forklift#6]
Would be awesome to update this to qb-target and polyzones or similar so it's cleaner looking.

Looks fun as though!

**Comment by DonHulieo** [comment]
Definitely something that was always planned, might be time to dust this one off and do it.

**Comment by nzkfc** [comment]
If you need a tester I have 180 keen forklift drivers to test with haha.

**Comment by DonHulieo** [comment]
Script is now updated with QBTarget support and a few extras 👌
