### ISSUE TITLE
Can only complete 1 order

### ISSUE THREAD

**Issue by ChickenDipper1** [DonHulieo/don-forklift#7]
After completing 1 order you have to cancel the job and then take a new order. 
If you try taking a new order after completing the first one it shows an error "someone is already doing this order". 
You have to click cancel order and then start again to do another job, rather than just being able to choose take order again.

Also if you try taking another order while sitting in your forklift you will fall through the floor and become invisible until you get out of the forklift.

**Comment by DonHulieo** [comment]
This issue should now be fixed, happy forklift driving!

**Comment by DonHulieo** [comment]
I do suggest hopping out of the forklift as there's an animation and a wait the player does while it spawns the pallets
