### ISSUE TITLE
QB-Target Changes

### ISSUE THREAD

**Issue by nzkfc** [DonHulieo/don-forklift#8]
Hi,

Tried this out since you added the changes, one thing I can suggest is:

- Add peds to use qb-target so it has more RP to it, otherwise you're looking for an invisible spot (this is more for use on maps that isn't that expensive paid one.

- Add ped for garage, but make it so when you choose "Get forklift" or something, that the spawn for the vehicle is obviously not on that ped, so you spawn into the vehicle away from it.

- Change the truck so it takes math.random ammounts, at the moment it seems to take one only, but would be cool to math.random it.

- What happens at the end of delivering a pallet and the truck goes? I drove forklift back to the sport to put it away but it doesn't allow it (I assume due to the qb-target stuff)

**Comment by DonHulieo** [comment]
The peds can be something that could be definitely added, I personally don't like that in roleplay but to each their own. I do plan on having the pick up vehicle take different amounts of pallets, but with putting the forklift away, it checks if you're in the vehicle. If you were trying to target the garage whilst outside the forklift, it wont do anything.

**Comment by nzkfc** [comment]
Ped interaction is more RP then a random draw text floating, but I get ya,
took me time to like target.

**Comment by DonHulieo** [comment]
I have no problem with target, I'd just rather target a laptop than a random ped  (just hard to find a suitable area for this that isn't an MLO)

**Comment by DonHulieo** [comment]
Just realised, if you have drawtext floating and you wanna just use target, set Config.UseTarget to true..... The draw text is only for if your not using qb-target.

**Comment by nzkfc** [comment]
Yeah I tried both but target was too hard without having something in our
warehouse mlo to target but that can be fixed by adding options for Ped
interaction.

**Comment by DonHulieo** [comment]
Recent update adds peds to locations (amongst other features) but this should resolve your issues.
