### ISSUE TITLE
Newest qbcore issues?

### ISSUE THREAD

**Issue by cfunkz** [DonHulieo/don-forklift#9]
1. No blip showing for driver pickup location.
2. When picking up new order after previous one it still shows 'Cancel Order' and 'Take Order' at the same time.
3. The delivery vans circle around the warehouse and don't despawn.

**Comment by DonHulieo** [comment]
1 - Should be Resolved, this was a typo on my behalf, as I forgot to define the entity to attach the blip to.
2 - Should be Resolved in latest Push
3- This is an issue with GTA's AI Pathing. If you continue to have issues with the truck deleting, edit line 145 in client/main.lua to a lower number. (This is the distance the truck must be from the player to delete).
